runtime: custom
env: flex
service: default
threadsafe: yes
network:
  forwarded_ports:
    - 80:8080
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
readiness_check:
  path: "/health"
  check_interval_sec: 15
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 10
liveness_check:
  path: "/health"
  check_interval_sec: 300
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
env_variables:
  SITOMAT_COLLECTION_USER: "firestore://projects/sit-o-mat-firestore/databases/(default)/documents/user?name_field=Name"
  SITOMAT_COLLECTION_WORKPLACE: "firestore://projects/sit-o-mat-firestore/databases/(default)/documents/workplace?name_field=Name"
  GOOGLE_APPLICATION_CREDENTIALS: "sit-o-mat-firestore.json"
  SITOMAT_ADDR: "0.0.0.0:8080"
  SITOMAT_ADMIN_USERNAME: "admin"
#  SITOMAT_ADMIN_PASSWORD: "SET_BEFORE_DEPLOY"
# volumes:
# - name: ramdisk1
#   volume_type: tmpfs
#   size_gb: 0.5