runtime: custom
env: flex
service: default
threadsafe: yes
network:
  forwarded_ports:
    - 80:8080
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
readiness_check:
  path: "/workplace"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 20
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
env_variables:
  SITOMAT_COLLECTION_USER: "mem://user/name"
  SITOMAT_COLLECTION_WORKPLACE: "mem://workplace/name"
  SITOMAT_ADDR: "0.0.0.0:8080"
  SITOMAT_ADMIN_USERNAME: "admin"
#  SITOMAT_ADMIN_PASSWORD: "SET_BEFORE_DEPLOY"
# volumes:
# - name: ramdisk1
#   volume_type: tmpfs
#   size_gb: 0.5