POST http://localhost:8080/user
Content-Type: application/json
Authorization: Basic admin password

{
    "Name": "p.mueller"
}

###

GET http://localhost:8080/user/p.mueller
Content-Type: application/json

###

PATCH http://localhost:8080/user/p.mueller
Content-Type: application/json
Authorization: Basic p.mueller A8eGmtDp

{
    "op": "replace",
    "path": "/WeeklyRequests",
    "value":  {
        "Montag": true,
        "Dienstag": true,
        "Mittwoch": true,
        "Donnerstag": true,
        "Freitag": true
    }
}

###
DELETE http://localhost:8080/user/p.mueller
Authorization: Basic admin password
